const fs = require('fs');
const html = [
'<!DOCTYPE html>',
'<html lang="mn">',
'<head>',
'<meta charset="UTF-8"/>',
'<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"/>',
'<title>MongoPoker</title>',
'<script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></scr'+'ipt>',
'<style>',
'*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}',
'body{background:#0a0e1a;color:#e6edf3;font-family:system-ui,sans-serif;max-width:430px;margin:0 auto;min-height:100vh;overflow-x:hidden;}',
'.page{display:none;min-height:100vh;}',
'.page.active{display:flex;flex-direction:column;}',

'/* AUTH */',
'.auth-bg{flex:1;display:flex;flex-direction:column;align-items:center;padding:40px 24px 24px;background:linear-gradient(180deg,#0d1a2e 0%,#0a0e1a 100%);}',
'.auth-logo{font-size:32px;font-weight:800;text-align:center;margin-bottom:6px;color:#fff;letter-spacing:-1px;}',
'.auth-logo span{color:#1D9E75;}',
'.auth-sub{font-size:13px;color:#555;margin-bottom:32px;text-align:center;}',
'.auth-card{background:#111827;border:1px solid #1f2937;border-radius:20px;padding:24px;width:100%;}',
'.tabs{display:flex;background:#0a0e1a;border-radius:12px;padding:3px;margin-bottom:20px;}',
'.tab{flex:1;padding:10px;border:none;background:transparent;color:#555;border-radius:10px;font-size:14px;cursor:pointer;font-weight:500;}',
'.tab.active{background:#1D9E75;color:#fff;font-weight:600;}',
'input{width:100%;background:#0a0e1a;border:1px solid #1f2937;border-radius:12px;padding:13px;color:#fff;font-size:15px;margin-bottom:12px;outline:none;}',
'input:focus{border-color:#1D9E75;}',
'input::placeholder{color:#333;}',
'.btn{width:100%;background:linear-gradient(135deg,#1D9E75,#157a5c);color:#fff;border:none;border-radius:12px;padding:15px;font-size:16px;font-weight:600;cursor:pointer;margin-bottom:8px;letter-spacing:0.3px;}',
'.err{color:#ff7b72;font-size:13px;margin-bottom:8px;min-height:18px;text-align:center;}',
'.bonus-tag{text-align:center;font-size:12px;color:#1D9E75;margin-top:8px;}',

'/* NAV */',
'.nav{display:flex;justify-content:space-between;align-items:center;background:#111827;padding:14px 16px;border-bottom:1px solid #1f2937;position:sticky;top:0;z-index:10;}',
'.nav-logo{font-size:20px;font-weight:800;color:#fff;letter-spacing:-0.5px;}',
'.nav-logo span{color:#1D9E75;}',
'.nav-right{display:flex;align-items:center;gap:8px;}',
'.chip-badge{background:#0d2818;border:1px solid #1D9E75;border-radius:20px;padding:5px 12px;font-size:13px;font-weight:600;color:#1D9E75;}',
'.nav-btn{background:#1f2937;color:#e6edf3;border:none;border-radius:10px;padding:7px 14px;font-size:13px;cursor:pointer;}',

'/* LOBBY */',
'.lobby-body{flex:1;overflow-y:auto;padding-bottom:20px;}',
'.lobby-banner{background:linear-gradient(135deg,#0d2818,#111827);padding:16px;margin:12px;border-radius:16px;border:1px solid #1D9E75;}',
'.banner-title{font-size:16px;font-weight:700;margin-bottom:4px;}',
'.banner-sub{font-size:12px;color:#666;}',
'.section-title{font-size:13px;font-weight:600;color:#555;padding:0 16px;margin:16px 0 8px;text-transform:uppercase;letter-spacing:0.5px;}',
'.filters{display:flex;gap:6px;padding:0 16px 12px;overflow-x:auto;}',
'.filters::-webkit-scrollbar{display:none;}',
'.fpill{white-space:nowrap;padding:7px 16px;border:1px solid #1f2937;border-radius:20px;font-size:12px;color:#666;background:#111827;cursor:pointer;font-weight:500;}',
'.fpill.active{background:#1D9E75;color:#fff;border-color:#1D9E75;}',
'.tlist{display:flex;flex-direction:column;gap:10px;padding:0 16px;}',
'.tcard{background:#111827;border:1px solid #1f2937;border-radius:16px;padding:16px;cursor:pointer;transition:border-color 0.2s;}',
'.tcard:active{border-color:#1D9E75;}',
'.tcard-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px;}',
'.tcard-name{font-size:16px;font-weight:700;color:#fff;}',
'.mbadge{display:inline-block;font-size:11px;padding:3px 10px;border-radius:8px;font-weight:600;}',
'.virtual{background:#0d2818;color:#1D9E75;}',
'.real{background:#2d1810;color:#EF9F27;}',
'.tcard-info{display:flex;gap:16px;margin-bottom:12px;}',
'.tinfo{display:flex;flex-direction:column;gap:2px;}',
'.tinfo-label{font-size:10px;color:#555;text-transform:uppercase;letter-spacing:0.3px;}',
'.tinfo-val{font-size:14px;font-weight:600;color:#fff;}',
'.tcard-footer{display:flex;justify-content:space-between;align-items:center;}',
'.seat-row{display:flex;gap:4px;}',
'.seat{width:10px;height:10px;border-radius:50%;background:#1f2937;}',
'.seat.on{background:#1D9E75;}',
'.join-btn{background:linear-gradient(135deg,#1D9E75,#157a5c);color:#fff;border:none;border-radius:10px;padding:8px 20px;font-size:13px;font-weight:600;cursor:pointer;}',

'/* PROFILE */',
'.profile-header{background:linear-gradient(180deg,#0d2818,#111827);padding:24px 16px;display:flex;flex-direction:column;align-items:center;gap:8px;}',
'.profile-avatar{width:72px;height:72px;border-radius:50%;background:linear-gradient(135deg,#1D9E75,#0d5c43);display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:800;color:#fff;border:3px solid #1D9E75;margin-bottom:4px;}',
'.profile-name{font-size:20px;font-weight:700;}',
'.profile-level{font-size:12px;color:#1D9E75;font-weight:600;}',
'.stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:16px;}',
'.stat-card{background:#111827;border:1px solid #1f2937;border-radius:14px;padding:14px;text-align:center;}',
'.stat-val{font-size:22px;font-weight:700;color:#1D9E75;margin-bottom:2px;}',
'.stat-label{font-size:11px;color:#555;}',

'/* WALLET */',
'.wallet-body{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px;}',
'.wallet-card{background:#111827;border:1px solid #1f2937;border-radius:16px;padding:18px;}',
'.wallet-label{font-size:12px;color:#555;margin-bottom:6px;}',
'.wallet-amount{font-size:28px;font-weight:700;}',
'.wallet-amount.green{color:#1D9E75;}',
'.amount-pills{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px;}',
'.apill{padding:8px 16px;border:1px solid #1f2937;border-radius:20px;font-size:13px;cursor:pointer;background:#0a0e1a;color:#666;}',
'.apill.active{border-color:#1D9E75;background:#0d2818;color:#1D9E75;}',
'.pay-select{width:100%;background:#0a0e1a;border:1px solid #1f2937;border-radius:12px;padding:12px;color:#fff;font-size:14px;margin-bottom:14px;outline:none;}',

'/* GAME */',
'.game-screen{flex:1;display:flex;flex-direction:column;background:#0a1f13;}',
'.game-nav{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;background:rgba(0,0,0,0.4);}',
'.game-nav button{background:rgba(255,255,255,0.1);color:#fff;border:none;border-radius:8px;padding:7px 13px;font-size:13px;cursor:pointer;}',
'.game-info{color:#FAC775;font-size:14px;font-weight:600;}',
'.felt{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:10px;}',
'.opp-row{display:flex;gap:12px;justify-content:center;margin-bottom:16px;flex-wrap:wrap;}',
'.opp-seat{display:flex;flex-direction:column;align-items:center;gap:3px;}',
'.opp-avatar{width:44px;height:44px;border-radius:50%;background:linear-gradient(135deg,#1f2937,#374151);display:flex;align-items:center;justify-content:center;font-size:16px;font-weight:700;color:#fff;border:2px solid #1f2937;}',
'.opp-avatar.active{border-color:#FAC775;}',
'.opp-name{font-size:10px;color:rgba(255,255,255,0.5);}',
'.opp-chips{font-size:11px;color:#FAC775;font-weight:600;}',
'.opp-cards{display:flex;gap:3px;justify-content:center;margin-top:2px;}',
'.card-back{width:18px;height:26px;background:linear-gradient(135deg,#1D9E75,#0d5c43);border-radius:3px;border:1px solid rgba(255,255,255,0.2);}',
'.pot-area{background:rgba(0,0,0,0.3);border-radius:12px;padding:8px 20px;margin-bottom:12px;}',
'.pot-label{font-size:11px;color:#555;text-align:center;}',
'.pot-amount{font-size:20px;font-weight:700;color:#FAC775;text-align:center;}',
'.community-cards{display:flex;gap:8px;justify-content:center;margin-bottom:16px;min-height:72px;align-items:center;}',
'.card{width:46px;height:66px;background:#fff;border-radius:8px;display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:14px;font-weight:800;color:#111;box-shadow:0 2px 8px rgba(0,0,0,0.4);}',
'.card.red{color:#e74c3c;}',
'.card.mine{border:2px solid #FAC775;box-shadow:0 0 10px rgba(250,199,117,0.4);}',
'.card-empty{width:46px;height:66px;border:1px dashed rgba(255,255,255,0.1);border-radius:8px;}',
'.my-cards{display:flex;gap:10px;justify-content:center;margin-bottom:16px;}',
'.action-area{background:rgba(0,0,0,0.4);padding:14px;border-radius:16px;margin:0 10px 10px;}',
'.action-row{display:flex;gap:8px;justify-content:center;margin-bottom:10px;}',
'.action-btn{padding:11px 18px;border:none;border-radius:12px;font-size:14px;font-weight:700;cursor:pointer;flex:1;}',
'.btn-fold{background:#c0392b;color:#fff;}',
'.btn-check{background:#374151;color:#fff;}',
'.btn-call{background:#2563eb;color:#fff;}',
'.btn-raise{background:linear-gradient(135deg,#1D9E75,#157a5c);color:#fff;}',
'.raise-row{display:flex;gap:8px;align-items:center;}',
'.raise-input{flex:1;text-align:center;margin-bottom:0;padding:10px;}',
'.game-log{padding:8px 16px;display:flex;flex-direction:column;gap:3px;max-height:80px;overflow:hidden;}',
'.log-item{font-size:11px;color:rgba(255,255,255,0.4);text-align:center;}',

'/* BOTTOM NAV */',
'.bottom-nav{display:flex;background:#111827;border-top:1px solid #1f2937;padding:8px 0 12px;}',
'.bnav{flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;cursor:pointer;padding:4px;}',
'.bnav-icon{font-size:20px;}',
'.bnav-label{font-size:10px;color:#555;font-weight:500;}',
'.bnav.active .bnav-label{color:#1D9E75;}',
'</style></head><body>',

'<!-- AUTH -->',
'<div class="page active" id="page-auth">',
'<div class="auth-bg">',
'<div class="auth-logo">Mongo<span>Poker</span></div>',
'<div class="auth-sub">Монголын хамгийн шилдэг покер</div>',
'<div class="auth-card">',
'<div class="tabs">',
'<button class="tab active" onclick="switchTab(\'login\')">Нэвтрэх</button>',
'<button class="tab" onclick="switchTab(\'register\')">Бүртгүүлэх</button>',
'</div>',
'<input id="auth-user" placeholder="Хэрэглэгчийн нэр"/>',
'<input id="auth-pass" type="password" placeholder="Нууц үг"/>',
'<div class="err" id="auth-err"></div>',
'<button class="btn" id="auth-btn" onclick="doAuth()">Нэвтрэх</button>',
'<div class="bonus-tag" id="bonus-tag"></div>',
'</div></div></div>',

'<!-- LOBBY -->',
'<div class="page" id="page-lobby">',
'<div class="nav">',
'<div class="nav-logo">Mongo<span>Poker</span></div>',
'<div class="nav-right">',
'<div class="chip-badge">🟢 <span id="lobby-chips">0</span></div>',
'<button class="nav-btn" onclick="showPage(\'profile\')">👤</button>',
'</div></div>',
'<div class="lobby-body">',
'<div class="lobby-banner">',
'<div class="banner-title">🎰 Өнөөдрийн тоглоом</div>',
'<div class="banner-sub">Шинэ тоглогч бүр 10,000 chip авна!</div>',
'</div>',
'<div class="section-title">Ширээнүүд</div>',
'<div class="filters">',
'<button class="fpill active" onclick="filterTable(this,\'all\')">Бүгд</button>',
'<button class="fpill" onclick="filterTable(this,\'holdem\')">Hold\'em</button>',
'<button class="fpill" onclick="filterTable(this,\'omaha\')">Omaha</button>',
'<button class="fpill" onclick="filterTable(this,\'fivecard\')">Five Card</button>',
'<button class="fpill" onclick="filterTable(this,\'virtual\')">Virtual</button>',
'<button class="fpill" onclick="filterTable(this,\'real\')">Жинхэнэ</button>',
'</div>',
'<div class="tlist" id="table-list"></div>',
'</div>',
'<div class="bottom-nav">',
'<div class="bnav active" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<!-- PROFILE -->',
'<div class="page" id="page-profile">',
'<div class="nav">',
'<div class="nav-logo">Профайл</div>',
'<button class="nav-btn" onclick="showPage(\'lobby\')">← Буцах</button>',
'</div>',
'<div class="profile-header">',
'<div class="profile-avatar" id="prof-avatar">?</div>',
'<div class="profile-name" id="prof-name"></div>',
'<div class="profile-level">🏆 Дунд түвшин</div>',
'</div>',
'<div class="stats-grid">',
'<div class="stat-card"><div class="stat-val" id="stat-chips">0</div><div class="stat-label">Virtual Chips</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-games">0</div><div class="stat-label">Тоглосон</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-wins">0</div><div class="stat-label">Хожсон</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-rate">0%</div><div class="stat-label">Хожлын %</div></div>',
'</div>',
'<div style="padding:16px;">',
'<button class="btn" onclick="logout()" style="background:#c0392b;">Гарах</button>',
'</div>',
'<div class="bottom-nav">',
'<div class="bnav" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav active" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<!-- WALLET -->',
'<div class="page" id="page-wallet">',
'<div class="nav">',
'<div class="nav-logo">Данс</div>',
'<button class="nav-btn" onclick="showPage(\'lobby\')">← Буцах</button>',
'</div>',
'<div class="wallet-body">',
'<div class="wallet-card">',
'<div class="wallet-label">Virtual Chips</div>',
'<div class="wallet-amount green" id="w-chips">0</div>',
'</div>',
'<div class="wallet-card">',
'<div class="wallet-label">Жинхэнэ мөнгө</div>',
'<div class="wallet-amount">₮0</div>',
'</div>',
'<div class="wallet-card">',
'<div style="font-size:15px;font-weight:700;margin-bottom:14px;">💳 Цэнэглэх</div>',
'<div class="amount-pills">',
'<div class="apill active" onclick="selAmt(this)">₮10,000</div>',
'<div class="apill" onclick="selAmt(this)">₮25,000</div>',
'<div class="apill" onclick="selAmt(this)">₮50,000</div>',
'<div class="apill" onclick="selAmt(this)">₮100,000</div>',
'</div>',
'<select class="pay-select">',
'<option>QPay</option>',
'<option>SocialPay</option>',
'<option>Khan Bank</option>',
'<option>Visa / Mastercard</option>',
'</select>',
'<button class="btn" onclick="alert(\'Цэнэглэлт амжилттай! (Demo)\')">Цэнэглэх</button>',
'</div></div>',
'<div class="bottom-nav">',
'<div class="bnav" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav active" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<!-- GAME -->',
'<div class="page" id="page-game">',
'<div class="game-screen">',
'<div class="game-nav">',
'<button onclick="showPage(\'lobby\')">← Гарах</button>',
'<div class="game-info">Пот: <span id="pot-val">0</span> 🪙</div>',
'<button style="background:#FAC775;color:#0a0e1a;font-weight:700;" onclick="startGame()">▶ Эхлэх</button>',
'</div>',
'<div class="felt">',
'<div class="opp-row" id="opps"></div>',
'<div class="pot-area"><div class="pot-label">ПОТ</div><div class="pot-amount" id="pot-display">0 🪙</div></div>',
'<div class="community-cards" id="community"></div>',
'<div class="my-cards" id="my-hand"></div>',
'</div>',
'<div class="action-area">',
'<div class="action-row">',
'<button class="action-btn btn-fold" onclick="act(\'fold\')">✕ Fold</button>',
'<button class="action-btn btn-check" onclick="act(\'check\')">— Check</button>',
'<button class="action-btn btn-call" onclick="act(\'call\',100)">↑ Call</button>',
'</div>',
'<div class="raise-row">',
'<input type="number" id="raise-amt" value="500" min="100" step="100" class="raise-input"/>',
'<button class="action-btn btn-raise" onclick="act(\'raise\',+document.getElementById(\'raise-amt\').value)" style="flex:1.5;">🔥 Raise</button>',
'</div>',
'</div>',
'<div class="game-log" id="game-log"></div>',
'</div></div>',

'<scr'+'ipt>',
'const SUITS={S:"♠",H:"♥",D:"♦",C:"♣"};',
'const RED={H:true,D:true};',
'const TABLES=[',
'{id:"room1",name:"Алтан ширээ",type:"holdem",blind:"500/1,000",mode:"virtual",max:6,players:3},',
'{id:"room2",name:"VIP Omaha",type:"omaha",blind:"5,000/10,000",mode:"real",max:6,players:1},',
'{id:"room3",name:"Эхлэгчдийн ширээ",type:"holdem",blind:"100/200",mode:"virtual",max:9,players:5},',
'{id:"room4",name:"Five Card Pro",type:"fivecard",blind:"1,000/2,000",mode:"virtual",max:6,players:2},',
'{id:"room5",name:"High Roller",type:"holdem",blind:"10,000/20,000",mode:"real",max:6,players:1},',
'{id:"room6",name:"Omaha Hi-Lo",type:"omaha",blind:"200/400",mode:"virtual",max:9,players:4},',
'];',
'let user=null,curRoom=null,socket=null,logItems=[],authTab="login",gamesPlayed=0,gamesWon=0;',
'function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById("page-"+p).classList.add("active");if(p==="profile")updateProfile();}',
'function switchTab(t){authTab=t;document.querySelectorAll(".tab").forEach((el,i)=>el.classList.toggle("active",i===(t==="login"?0:1)));document.getElementById("auth-btn").textContent=t==="login"?"Нэвтрэх":"Бүртгүүлэх";document.getElementById("bonus-tag").textContent=t==="register"?"🎁 Шинэ тоглогч 10,000 chip авна!":"";}',
'async function doAuth(){const u=document.getElementById("auth-user").value.trim();const p=document.getElementById("auth-pass").value.trim();if(!u||!p){document.getElementById("auth-err").textContent="Нэр болон нууц үгээ оруулна уу";return;}try{const res=await fetch("https://8b0004e3074ef5.lhr.life/api/"+authTab,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:u,password:p})});const data=await res.json();if(data.error){document.getElementById("auth-err").textContent=data.error;return;}user=data;updateChips();renderTables("all");initSocket();showPage("lobby");}catch(e){document.getElementById("auth-err").textContent="Сервертэй холбогдож чадсангүй";}}',
'function updateChips(){document.getElementById("lobby-chips").textContent=Number(user.chips).toLocaleString();document.getElementById("w-chips").textContent=Number(user.chips).toLocaleString();}',
'function updateProfile(){if(!user)return;document.getElementById("prof-avatar").textContent=user.username[0].toUpperCase();document.getElementById("prof-name").textContent=user.username;document.getElementById("stat-chips").textContent=Number(user.chips).toLocaleString();document.getElementById("stat-games").textContent=gamesPlayed;document.getElementById("stat-wins").textContent=gamesWon;document.getElementById("stat-rate").textContent=gamesPlayed?Math.round(gamesWon/gamesPlayed*100)+"%":"0%";}',
'function logout(){user=null;if(socket)socket.disconnect();showPage("auth");}',
'function renderTables(filter){const list=document.getElementById("table-list");const filtered=filter==="all"?TABLES:TABLES.filter(t=>t.type===filter||t.mode===filter);list.innerHTML=filtered.map(t=>{const seats=Array(t.max).fill(0).map((_,i)=>"<div class=\\"seat"+(i<t.players?" on":"")+"\\" ></div>").join("");return "<div class=\\"tcard\\"><div class=\\"tcard-top\\"><div class=\\"tcard-name\\">"+t.name+"</div><div class=\\"mbadge "+(t.mode==="virtual"?"virtual":"real")+"\\">"+( t.mode==="virtual"?"Virtual":"💰 Жинхэнэ")+"</div></div><div class=\\"tcard-info\\"><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Төрөл</div><div class=\\"tinfo-val\\">"+t.type+"</div></div><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Блайнд</div><div class=\\"tinfo-val\\">"+t.blind+"</div></div><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Тоглогч</div><div class=\\"tinfo-val\\">"+t.players+"/"+t.max+"</div></div></div><div class=\\"tcard-footer\\"><div class=\\"seat-row\\">"+seats+"</div><button class=\\"join-btn\\" onclick=\\"joinRoom(\'"+t.id+"\')\\" >Нэгдэх</button></div></div>";}).join("");}',
'function filterTable(btn,f){document.querySelectorAll(".fpill").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderTables(f);}',
'function joinRoom(id){curRoom=id;document.getElementById("pot-val").textContent="0";document.getElementById("pot-display").textContent="0 🪙";document.getElementById("community").innerHTML="";document.getElementById("my-hand").innerHTML="";document.getElementById("opps").innerHTML="";logItems=[];document.getElementById("game-log").innerHTML="";if(socket)socket.emit("join_room",{room:id,username:user.username});gamesPlayed++;showPage("game");}',
'function initSocket(){socket=io("https://8b0004e3074ef5.lhr.life");socket.on("room_update",r=>{const others=r.players.filter(p=>p.username!==user.username);document.getElementById("opps").innerHTML=others.map(p=>"<div class=\\"opp-seat\\"><div class=\\"opp-avatar\\">"+p.username[0].toUpperCase()+"</div><div class=\\"opp-cards\\"><div class=\\"card-back\\"></div><div class=\\"card-back\\"></div></div><div class=\\"opp-name\\">"+p.username+"</div><div class=\\"opp-chips\\">"+Number(p.chips).toLocaleString()+" 🪙</div></div>").join("");});socket.on("game_started",r=>{document.getElementById("pot-val").textContent="0";document.getElementById("pot-display").textContent="0 🪙";document.getElementById("community").innerHTML="<div class=\\"card-empty\\"></div><div class=\\"card-empty\\"></div><div class=\\"card-empty\\"></div><div class=\\"card-empty\\"></div><div class=\\"card-empty\\"></div>";const me=r.players.find(p=>p.username===user.username);if(me)document.getElementById("my-hand").innerHTML=me.hand.map(c=>"<div class=\\"card"+(RED[c.suit]?" red":"")+" mine\\"><span>"+c.rank+"</span><span>"+SUITS[c.suit]+"</span></div>").join("");addLog("🃏 Тоглоом эхэллээ!");});socket.on("community_update",cards=>{const empty=5-cards.length;document.getElementById("community").innerHTML=cards.map(c=>"<div class=\\"card"+(RED[c.suit]?" red":"")+"\\"><span>"+c.rank+"</span><span>"+SUITS[c.suit]+"</span></div>").join("")+Array(empty).fill("<div class=\\"card-empty\\"></div>").join("");});socket.on("player_action",function(d){if(d.pot){document.getElementById("pot-val").textContent=Number(d.pot).toLocaleString();document.getElementById("pot-display").textContent=Number(d.pot).toLocaleString()+" 🪙";}addLog(d.username+": "+d.action+(d.amount?" "+Number(d.amount).toLocaleString()+" 🪙":""));});}',
'function startGame(){if(socket&&curRoom)socket.emit("start_game",curRoom);}',
'function act(a,amt){if(socket&&curRoom)socket.emit("action",{room:curRoom,action:a,amount:amt,username:user.username});}',
'function addLog(m){logItems=[m,...logItems].slice(0,4);document.getElementById("game-log").innerHTML=logItems.map(l=>"<div class=\\"log-item\\">"+l+"</div>").join("");}',
'function selAmt(el){document.querySelectorAll(".apill").forEach(p=>p.classList.remove("active"));el.classList.add("active");}',
'</scr'+'ipt></body></html>'
].join("\n");

fs.writeFileSync('index.html', html);
console.log('Done! Size:', html.length);
