const fs = require('fs');
const url = 'https://32cabf61343f40.lhr.life';
const html = [
'<!DOCTYPE html>',
'<html lang="mn"><head>',
'<meta charset="UTF-8"/>',
'<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/>',
'<title>Royal Flush Poker</title>',
'<script src="https://cdn.socket.io/4.7.2/socket.io.min.js"></scr'+'ipt>',
'<style>',
'@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700;800&family=Inter:wght@400;500;600;700&display=swap");',
'*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent;}',
'body{background:#06080f;color:#e8dcc8;font-family:"Inter",system-ui,sans-serif;max-width:430px;margin:0 auto;min-height:100vh;overflow-x:hidden;}',
':root{--gold:#c9a84c;--gold2:#f0d080;--dark:#06080f;--c1:#0c1018;--c2:#111827;--border:#1a2030;--felt:#071a0f;}',
'.page{display:none;min-height:100vh;flex-direction:column;}',
'.page.active{display:flex;}',

/* AUTH */
'@keyframes fadeIn{from{opacity:0;transform:translateY(10px);}to{opacity:1;transform:translateY(0);}}',
'.auth-bg{flex:1;display:flex;flex-direction:column;background:linear-gradient(180deg,#0a1220,#06080f);}',
'.auth-hero{padding:48px 24px 32px;display:flex;flex-direction:column;align-items:center;background:linear-gradient(135deg,#0a1a10,#0d1525);border-bottom:1px solid rgba(201,168,76,0.1);}',
'.auth-crown{font-size:48px;margin-bottom:12px;animation:fadeIn 0.5s ease;}',
'.auth-logo{font-family:"Playfair Display",serif;font-size:28px;font-weight:800;color:var(--gold);text-shadow:0 0 30px rgba(201,168,76,0.3);letter-spacing:1px;}',
'.auth-sub{font-size:11px;color:#444;letter-spacing:3px;text-transform:uppercase;margin-top:8px;}',
'.auth-form{padding:24px;}',
'.auth-card{background:var(--c1);border:1px solid var(--border);border-radius:20px;padding:24px;}',
'.tabs{display:flex;background:var(--dark);border-radius:12px;padding:3px;margin-bottom:20px;border:1px solid var(--border);}',
'.tab{flex:1;padding:10px;border:none;background:transparent;color:#555;border-radius:10px;font-size:14px;cursor:pointer;font-weight:500;}',
'.tab.active{background:linear-gradient(135deg,#b8860b,#c9a84c);color:#06080f;font-weight:700;}',
'.flabel{font-size:11px;color:#555;letter-spacing:1px;text-transform:uppercase;margin-bottom:6px;display:block;}',
'input{width:100%;background:var(--dark);border:1px solid var(--border);border-radius:12px;padding:13px 16px;color:#e8dcc8;font-size:15px;margin-bottom:16px;outline:none;}',
'input:focus{border-color:var(--gold);}',
'input::placeholder{color:#2a2a2a;}',
'.btn-gold{width:100%;background:linear-gradient(135deg,#b8860b,#c9a84c,#f0d080);color:#06080f;border:none;border-radius:12px;padding:15px;font-size:16px;font-weight:700;cursor:pointer;}',
'.btn-gold:active{opacity:0.9;transform:scale(0.99);}',
'.err{color:#e05555;font-size:13px;margin-bottom:10px;min-height:18px;text-align:center;}',
'.bonus-tag{text-align:center;font-size:12px;color:var(--gold);margin-top:10px;}',

/* NAV */
'.nav{display:flex;justify-content:space-between;align-items:center;background:var(--c1);padding:14px 16px;border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100;}',
'.nav-logo{font-family:"Playfair Display",serif;font-size:18px;font-weight:700;color:var(--gold);}',
'.nav-right{display:flex;align-items:center;gap:8px;}',
'.chip-badge{background:rgba(201,168,76,0.08);border:1px solid rgba(201,168,76,0.3);border-radius:20px;padding:6px 14px;font-size:13px;font-weight:700;color:var(--gold);}',
'.nav-btn{background:var(--c2);color:#e8dcc8;border:1px solid var(--border);border-radius:10px;padding:7px 12px;font-size:13px;cursor:pointer;}',

/* LOBBY */
'.lobby-body{flex:1;overflow-y:auto;padding-bottom:80px;}',
'.lobby-banner{background:linear-gradient(135deg,#0a1f13,#0d1525);padding:20px;margin:12px;border-radius:20px;border:1px solid rgba(201,168,76,0.2);position:relative;overflow:hidden;}',
'.lobby-banner::after{content:"♠";position:absolute;right:-15px;bottom:-15px;font-size:100px;opacity:0.04;color:var(--gold);}',
'.banner-title{font-family:"Playfair Display",serif;font-size:20px;font-weight:700;color:var(--gold);margin-bottom:4px;}',
'.banner-sub{font-size:12px;color:#555;margin-bottom:8px;}',
'.banner-chip{display:inline-block;font-size:12px;color:var(--gold);font-weight:600;background:rgba(201,168,76,0.1);border:1px solid rgba(201,168,76,0.2);border-radius:20px;padding:4px 12px;}',
'.sec-title{font-size:11px;font-weight:600;color:#333;padding:0 16px;margin:16px 0 8px;text-transform:uppercase;letter-spacing:1.5px;}',
'.filters{display:flex;gap:6px;padding:0 16px 12px;overflow-x:auto;}',
'.filters::-webkit-scrollbar{display:none;}',
'.fpill{white-space:nowrap;padding:7px 16px;border:1px solid var(--border);border-radius:20px;font-size:12px;color:#444;background:var(--c1);cursor:pointer;}',
'.fpill.active{background:rgba(201,168,76,0.1);color:var(--gold);border-color:rgba(201,168,76,0.4);}',
'.tlist{display:flex;flex-direction:column;gap:12px;padding:0 16px;}',
'.tcard{background:var(--c1);border:1px solid var(--border);border-radius:20px;padding:18px;position:relative;overflow:hidden;}',
'.tcard-shine{position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,rgba(201,168,76,0.3),transparent);}',
'.tcard-top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:14px;}',
'.tcard-name{font-family:"Playfair Display",serif;font-size:17px;font-weight:700;color:#e8dcc8;}',
'.mbadge{display:inline-block;font-size:11px;padding:4px 12px;border-radius:10px;font-weight:600;}',
'.virtual{background:rgba(13,92,58,0.2);color:#2ecc71;border:1px solid rgba(46,204,113,0.2);}',
'.real{background:rgba(184,134,11,0.15);color:var(--gold);border:1px solid rgba(201,168,76,0.25);}',
'.tcard-info{display:flex;gap:0;margin-bottom:14px;background:rgba(0,0,0,0.3);border-radius:12px;overflow:hidden;border:1px solid var(--border);}',
'.tinfo{flex:1;padding:10px;text-align:center;border-right:1px solid var(--border);}',
'.tinfo:last-child{border-right:none;}',
'.tinfo-label{font-size:9px;color:#333;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px;}',
'.tinfo-val{font-size:13px;font-weight:700;color:#e8dcc8;}',
'.tcard-footer{display:flex;justify-content:space-between;align-items:center;}',
'.seat-row{display:flex;gap:4px;align-items:center;}',
'.seat{width:9px;height:9px;border-radius:50%;background:var(--border);}',
'.seat.on{background:var(--gold);box-shadow:0 0 4px rgba(201,168,76,0.5);}',
'.seat-count{font-size:11px;color:#333;margin-left:4px;}',
'.join-btn{background:linear-gradient(135deg,#b8860b,#c9a84c);color:#06080f;border:none;border-radius:12px;padding:9px 20px;font-size:13px;font-weight:700;cursor:pointer;}',

/* JOIN MODAL */
'.modal-bg{position:fixed;inset:0;background:rgba(0,0,0,0.8);z-index:200;display:flex;align-items:flex-end;justify-content:center;}',
'.modal-bg.hidden{display:none;}',
'.modal{background:var(--c1);border:1px solid var(--border);border-radius:24px 24px 0 0;padding:28px 24px 40px;width:100%;max-width:430px;animation:slideUp 0.3s ease;}',
'@keyframes slideUp{from{transform:translateY(100%);}to{transform:translateY(0);}}',
'.modal-title{font-family:"Playfair Display",serif;font-size:20px;font-weight:700;color:var(--gold);margin-bottom:4px;}',
'.modal-sub{font-size:13px;color:#555;margin-bottom:20px;}',
'.modal-table-name{font-size:15px;font-weight:600;color:#e8dcc8;margin-bottom:20px;padding:12px;background:rgba(0,0,0,0.3);border-radius:12px;border:1px solid var(--border);text-align:center;}',
'.modal-btn{width:100%;padding:15px;border:none;border-radius:12px;font-size:16px;font-weight:700;cursor:pointer;margin-bottom:10px;}',
'.modal-btn.primary{background:linear-gradient(135deg,#b8860b,#c9a84c);color:#06080f;}',
'.modal-btn.secondary{background:var(--c2);color:#e8dcc8;border:1px solid var(--border);}',

/* PROFILE */
'.prof-hero{background:linear-gradient(180deg,#0a1f13,#06080f);padding:32px 16px 24px;display:flex;flex-direction:column;align-items:center;gap:10px;border-bottom:1px solid var(--border);}',
'.prof-avatar{width:84px;height:84px;border-radius:50%;background:linear-gradient(135deg,#b8860b,#c9a84c);display:flex;align-items:center;justify-content:center;font-size:34px;font-weight:800;color:#06080f;border:3px solid var(--gold);box-shadow:0 0 24px rgba(201,168,76,0.25);}',
'.prof-name{font-family:"Playfair Display",serif;font-size:22px;font-weight:700;}',
'.prof-badge{background:rgba(201,168,76,0.1);border:1px solid rgba(201,168,76,0.25);border-radius:20px;padding:4px 16px;font-size:12px;color:var(--gold);}',
'.prof-level{font-size:11px;color:#555;letter-spacing:2px;text-transform:uppercase;}',
'.stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:16px;}',
'.stat-card{background:var(--c1);border:1px solid var(--border);border-radius:16px;padding:16px;text-align:center;}',
'.stat-val{font-family:"Playfair Display",serif;font-size:24px;font-weight:700;color:var(--gold);margin-bottom:4px;}',
'.stat-label{font-size:10px;color:#333;text-transform:uppercase;letter-spacing:0.5px;}',
'.logout-btn{width:calc(100% - 32px);margin:0 16px 16px;background:rgba(180,40,30,0.1);color:#e05555;border:1px solid rgba(180,40,30,0.25);border-radius:12px;padding:14px;font-size:15px;font-weight:600;cursor:pointer;}',

/* WALLET */
'.wallet-body{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px;padding-bottom:80px;}',
'.wallet-card{background:var(--c1);border:1px solid var(--border);border-radius:20px;padding:20px;}',
'.w-label{font-size:11px;color:#333;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px;}',
'.w-amount{font-size:32px;font-weight:700;font-family:"Playfair Display",serif;}',
'.w-amount.gold{color:var(--gold);}',
'.deposit-section{background:var(--c1);border:1px solid var(--border);border-radius:20px;padding:20px;}',
'.deposit-title{font-family:"Playfair Display",serif;font-size:17px;color:var(--gold);margin-bottom:16px;}',
'.amount-pills{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px;}',
'.apill{padding:9px 16px;border:1px solid var(--border);border-radius:12px;font-size:13px;cursor:pointer;background:var(--dark);color:#444;font-weight:500;}',
'.apill.active{border-color:var(--gold);background:rgba(201,168,76,0.08);color:var(--gold);}',
'.pay-methods{display:flex;flex-direction:column;gap:8px;margin-bottom:16px;}',
'.pay-method{display:flex;align-items:center;gap:12px;padding:13px;background:var(--dark);border:1px solid var(--border);border-radius:12px;cursor:pointer;}',
'.pay-method.selected{border-color:var(--gold);background:rgba(201,168,76,0.05);}',
'.pay-icon{font-size:24px;}',
'.pay-name{font-size:14px;font-weight:600;color:#e8dcc8;}',
'.pay-sub{font-size:11px;color:#444;}',
'.pay-radio{width:18px;height:18px;border-radius:50%;border:2px solid var(--border);margin-left:auto;display:flex;align-items:center;justify-content:center;}',
'.pay-radio.on{border-color:var(--gold);}',
'.pay-radio.on::after{content:"";width:8px;height:8px;border-radius:50%;background:var(--gold);}',

/* GAME */
'.game-screen{flex:1;display:flex;flex-direction:column;background:var(--felt);}',
'.game-nav{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;background:rgba(0,0,0,0.6);border-bottom:1px solid rgba(201,168,76,0.1);}',
'.game-nav-btn{background:rgba(255,255,255,0.07);color:#e8dcc8;border:1px solid rgba(255,255,255,0.12);border-radius:10px;padding:7px 13px;font-size:13px;cursor:pointer;}',
'.game-title{font-family:"Playfair Display",serif;font-size:15px;color:var(--gold);}',
'.game-phase{font-size:11px;color:rgba(201,168,76,0.5);text-transform:uppercase;letter-spacing:1px;}',
'.felt-area{flex:1;display:flex;flex-direction:column;align-items:center;padding:8px;background:radial-gradient(ellipse at center,#0d2818 0%,#071a0f 60%,#040e08 100%);position:relative;}',
'.felt-area::before{content:"";position:absolute;inset:8px;border-radius:50%;border:2px solid rgba(201,168,76,0.1);pointer-events:none;}',

/* SEATS */
'.opp-seats{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;width:100%;padding:6px 4px;z-index:2;}',
'.seat-wrap{display:flex;flex-direction:column;align-items:center;gap:3px;min-width:62px;}',
'.player-seat{background:rgba(0,0,0,0.5);border:1px solid rgba(201,168,76,0.1);border-radius:14px;padding:8px 6px;display:flex;flex-direction:column;align-items:center;gap:3px;width:100%;}',
'.player-seat.my-turn{border-color:var(--gold);box-shadow:0 0 12px rgba(201,168,76,0.2);}',
'.player-seat.folded{opacity:0.4;}',
'.p-avatar{width:40px;height:40px;border-radius:50%;background:linear-gradient(135deg,#1a2535,#243050);display:flex;align-items:center;justify-content:center;font-size:15px;font-weight:700;color:#e8dcc8;border:2px solid rgba(201,168,76,0.15);position:relative;}',
'.dealer-d{position:absolute;top:-4px;right:-4px;width:15px;height:15px;background:var(--gold);border-radius:50%;font-size:8px;display:flex;align-items:center;justify-content:center;color:#06080f;font-weight:800;}',
'.p-back-cards{display:flex;gap:2px;}',
'.card-back{width:16px;height:24px;background:linear-gradient(135deg,#0d5c3a,#0a3d26);border-radius:3px;border:1px solid rgba(255,255,255,0.1);}',
'.p-name{font-size:9px;color:rgba(255,255,255,0.35);text-align:center;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
'.p-chips{font-size:11px;color:var(--gold);font-weight:600;}',
'.empty-seat-wrap{background:rgba(0,0,0,0.2);border:1px dashed rgba(255,255,255,0.06);border-radius:14px;padding:8px 6px;display:flex;flex-direction:column;align-items:center;gap:3px;width:100%;min-width:62px;opacity:0.3;}',
'.empty-seat-icon{font-size:20px;color:rgba(255,255,255,0.2);}',
'.empty-seat-txt{font-size:9px;color:rgba(255,255,255,0.2);}',

/* TABLE */
'.table-oval{width:100%;background:radial-gradient(ellipse,#0f2d1a 0%,#0a2014 50%,#071a0f 100%);border-radius:70px;padding:14px 10px;margin:4px 0;border:2px solid rgba(201,168,76,0.1);box-shadow:inset 0 0 40px rgba(0,0,0,0.6);position:relative;}',
'.table-oval::before{content:"";position:absolute;inset:5px;border-radius:65px;border:1px solid rgba(201,168,76,0.05);}',
'.pot-row{display:flex;justify-content:center;align-items:center;gap:8px;margin-bottom:10px;}',
'.pot-chip{width:30px;height:30px;border-radius:50%;background:linear-gradient(135deg,#b8860b,#c9a84c);border:3px solid rgba(255,255,255,0.2);display:flex;align-items:center;justify-content:center;font-size:13px;}',
'.pot-val{font-family:"Playfair Display",serif;font-size:18px;font-weight:700;color:var(--gold);}',
'.pot-lbl{font-size:9px;color:#333;text-transform:uppercase;letter-spacing:1px;}',
'.community-cards{display:flex;gap:5px;justify-content:center;}',
'.card{width:40px;height:58px;background:linear-gradient(180deg,#fff,#f5f5f5);border-radius:7px;display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:12px;font-weight:800;color:#111;box-shadow:0 4px 12px rgba(0,0,0,0.6);gap:0;}',
'.card.red{color:#c0392b;}',
'.card.mine{border:2px solid var(--gold);box-shadow:0 0 14px rgba(201,168,76,0.5);}',
'@keyframes deal{from{transform:scale(0.3) rotate(-15deg);opacity:0;}to{transform:scale(1) rotate(0);opacity:1;}}',
'.card.deal{animation:deal 0.35s cubic-bezier(0.34,1.56,0.64,1);}',
'.card-rank{font-size:13px;font-weight:800;line-height:1.1;}',
'.card-suit{font-size:15px;line-height:1.1;}',
'.card-empty{width:40px;height:58px;border:1px dashed rgba(255,255,255,0.07);border-radius:7px;background:rgba(255,255,255,0.02);}',

/* MY HAND */
'.my-hand-area{display:flex;flex-direction:column;align-items:center;gap:5px;margin:4px 0 6px;}',
'.my-hand-lbl{font-size:10px;color:rgba(201,168,76,0.4);text-transform:uppercase;letter-spacing:1.5px;}',
'.my-cards{display:flex;gap:12px;}',

/* WAITING */
'.waiting-msg{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:20px;color:rgba(255,255,255,0.3);}',
'.waiting-icon{font-size:32px;}',
'.waiting-txt{font-size:13px;letter-spacing:0.5px;}',
'@keyframes pulse{0%,100%{opacity:0.3;}50%{opacity:0.8;}}',
'.waiting-dots{animation:pulse 1.5s infinite;}',

/* ACTION */
'.action-panel{background:linear-gradient(180deg,rgba(0,0,0,0.7),rgba(6,8,15,0.95));padding:12px 12px 18px;border-top:1px solid rgba(201,168,76,0.1);}',
'.table-info{display:flex;justify-content:center;gap:16px;margin-bottom:10px;}',
'.tbl-info-item{font-size:11px;color:#333;text-align:center;}',
'.tbl-info-val{color:rgba(201,168,76,0.6);font-weight:600;}',
'.turn-indicator{text-align:center;font-size:12px;color:var(--gold);margin-bottom:8px;min-height:18px;font-weight:600;}',
'.action-row{display:flex;gap:7px;margin-bottom:10px;}',
'.action-btn{flex:1;padding:13px 6px;border:none;border-radius:13px;font-size:14px;font-weight:700;cursor:pointer;}',
'.action-btn:active{transform:scale(0.96);}',
'.btn-fold{background:rgba(180,40,30,0.15);color:#e05555;border:1px solid rgba(180,40,30,0.3);}',
'.btn-check{background:rgba(255,255,255,0.06);color:#aaa;border:1px solid rgba(255,255,255,0.1);}',
'.btn-call{background:rgba(30,80,200,0.2);color:#6fa8ff;border:1px solid rgba(30,80,200,0.35);}',
'.raise-row{display:flex;gap:8px;align-items:center;margin-bottom:8px;}',
'.raise-slider{flex:1;-webkit-appearance:none;height:4px;border-radius:2px;background:var(--border);outline:none;}',
'.raise-slider::-webkit-slider-thumb{-webkit-appearance:none;width:20px;height:20px;border-radius:50%;background:var(--gold);cursor:pointer;box-shadow:0 0 8px rgba(201,168,76,0.4);}',
'.raise-display{font-size:13px;color:var(--gold);font-weight:700;min-width:72px;text-align:center;background:rgba(201,168,76,0.07);border:1px solid rgba(201,168,76,0.18);border-radius:8px;padding:6px;}',
'.btn-raise{padding:13px 14px;border:none;border-radius:13px;font-size:14px;font-weight:700;cursor:pointer;background:linear-gradient(135deg,#b8860b,#c9a84c);color:#06080f;white-space:nowrap;}',
'.btn-raise:active{transform:scale(0.96);}',
'.deal-row{display:flex;gap:7px;}',
'.deal-btn{flex:1;padding:10px;border:none;border-radius:11px;font-size:12px;font-weight:600;cursor:pointer;background:rgba(255,255,255,0.05);color:#666;border:1px solid rgba(255,255,255,0.08);}',
'.deal-btn:active{background:rgba(255,255,255,0.1);}',
'.game-log{padding:5px 16px 2px;display:flex;flex-direction:column;gap:2px;min-height:30px;}',
'.log-item{font-size:11px;color:rgba(255,255,255,0.22);text-align:center;}',

/* BOTTOM NAV */
'.bottom-nav{display:flex;background:var(--c1);border-top:1px solid var(--border);padding:10px 0 16px;position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:100%;max-width:430px;z-index:50;}',
'.bnav{flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;cursor:pointer;padding:4px;}',
'.bnav-icon{font-size:22px;}',
'.bnav-label{font-size:10px;color:#333;font-weight:500;}',
'.bnav.active .bnav-label{color:var(--gold);}',
'</style></head><body>',

'<div class="page active" id="page-auth">',
'<div class="auth-bg">',
'<div class="auth-hero">',
'<div class="auth-crown">👑</div>',
'<div class="auth-logo">Royal Flush Poker</div>',
'<div class="auth-sub">Монголын хамгийн шилдэг покер</div>',
'</div>',
'<div class="auth-form"><div class="auth-card">',
'<div class="tabs">',
'<button class="tab active" onclick="switchTab(\'login\')">Нэвтрэх</button>',
'<button class="tab" onclick="switchTab(\'register\')">Бүртгүүлэх</button>',
'</div>',
'<label class="flabel">Хэрэглэгчийн нэр</label>',
'<input id="auth-user" placeholder="Нэрээ оруулна уу"/>',
'<label class="flabel">Нууц үг</label>',
'<input id="auth-pass" type="password" placeholder="••••••••"/>',
'<div class="err" id="auth-err"></div>',
'<button class="btn-gold" id="auth-btn" onclick="doAuth()">Нэвтрэх</button>',
'<div class="bonus-tag" id="bonus-tag"></div>',
'</div></div></div></div>',

'<div class="page" id="page-lobby">',
'<div class="nav"><div class="nav-logo">♠ Royal Flush</div>',
'<div class="nav-right">',
'<div class="chip-badge">🪙 <span id="lobby-chips">0</span></div>',
'<button class="nav-btn" onclick="showPage(\'profile\')">👤</button>',
'</div></div>',
'<div class="lobby-body">',
'<div class="lobby-banner">',
'<div class="banner-title">♠ Royal Tables</div>',
'<div class="banner-sub">Шилдэг тоглогчдын нэгдэл</div>',
'<div class="banner-chip">🎁 Шинэ тоглогч 10,000 chip авна</div>',
'</div>',
'<div class="sec-title">Покер ширээнүүд</div>',
'<div class="filters">',
'<button class="fpill active" onclick="filterTable(this,\'all\')">Бүгд</button>',
'<button class="fpill" onclick="filterTable(this,\'holdem\')">Texas Hold\'em</button>',
'<button class="fpill" onclick="filterTable(this,\'omaha\')">Omaha</button>',
'<button class="fpill" onclick="filterTable(this,\'fivecard\')">Five Card</button>',
'<button class="fpill" onclick="filterTable(this,\'virtual\')">Virtual</button>',
'<button class="fpill" onclick="filterTable(this,\'real\')">💰 Жинхэнэ</button>',
'</div>',
'<div class="tlist" id="table-list"></div>',
'</div>',
'<div class="bottom-nav">',
'<div class="bnav active" id="bnav-lobby" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav" id="bnav-profile" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav" id="bnav-wallet" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<div class="modal-bg hidden" id="join-modal">',
'<div class="modal">',
'<div class="modal-title">Ширээнд нэгдэх</div>',
'<div class="modal-sub">Та энэ ширээнд суух уу?</div>',
'<div class="modal-table-name" id="modal-table-name"></div>',
'<button class="modal-btn primary" onclick="confirmJoin()">🪑 Суух</button>',
'<button class="modal-btn secondary" onclick="closeModal()">Болих</button>',
'</div></div>',

'<div class="page" id="page-profile">',
'<div class="nav"><div class="nav-logo">♠ Профайл</div>',
'<button class="nav-btn" onclick="showPage(\'lobby\')">← Буцах</button></div>',
'<div style="flex:1;overflow-y:auto;padding-bottom:80px;">',
'<div class="prof-hero">',
'<div class="prof-avatar" id="prof-avatar">?</div>',
'<div class="prof-name" id="prof-name"></div>',
'<div class="prof-badge">👑 Royal Member</div>',
'<div class="prof-level" id="prof-level">BRONZE PLAYER</div>',
'</div>',
'<div class="stats-grid">',
'<div class="stat-card"><div class="stat-val" id="stat-chips">0</div><div class="stat-label">Chips</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-games">0</div><div class="stat-label">Тоглосон</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-wins">0</div><div class="stat-label">Хожсон</div></div>',
'<div class="stat-card"><div class="stat-val" id="stat-rate">0%</div><div class="stat-label">Хожлын %</div></div>',
'</div>',
'<button class="logout-btn" onclick="logout()">Гарах</button>',
'</div>',
'<div class="bottom-nav">',
'<div class="bnav" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav active" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<div class="page" id="page-wallet">',
'<div class="nav"><div class="nav-logo">♠ Данс</div>',
'<button class="nav-btn" onclick="showPage(\'lobby\')">← Буцах</button></div>',
'<div class="wallet-body">',
'<div class="wallet-card">',
'<div class="w-label">Virtual Chips</div>',
'<div class="w-amount gold" id="w-chips">0</div>',
'</div>',
'<div class="wallet-card">',
'<div class="w-label">Жинхэнэ мөнгө</div>',
'<div class="w-amount">₮0</div>',
'</div>',
'<div class="deposit-section">',
'<div class="deposit-title">💳 Цэнэглэх</div>',
'<div class="amount-pills">',
'<div class="apill active" onclick="selAmt(this,10000)">₮10,000</div>',
'<div class="apill" onclick="selAmt(this,25000)">₮25,000</div>',
'<div class="apill" onclick="selAmt(this,50000)">₮50,000</div>',
'<div class="apill" onclick="selAmt(this,100000)">₮100,000</div>',
'</div>',
'<div class="pay-methods" id="pay-methods">',
'<div class="pay-method selected" onclick="selPay(this,\'qpay\')"><div class="pay-icon">📱</div><div><div class="pay-name">QPay</div><div class="pay-sub">Шуурхай шилжүүлэг</div></div><div class="pay-radio on" id="radio-qpay"></div></div>',
'<div class="pay-method" onclick="selPay(this,\'social\')"><div class="pay-icon">🏦</div><div><div class="pay-name">SocialPay</div><div class="pay-sub">Голомт банк</div></div><div class="pay-radio" id="radio-social"></div></div>',
'<div class="pay-method" onclick="selPay(this,\'khan\')"><div class="pay-icon">🦁</div><div><div class="pay-name">Khan Bank</div><div class="pay-sub">Хаан банк</div></div><div class="pay-radio" id="radio-khan"></div></div>',
'<div class="pay-method" onclick="selPay(this,\'visa\')"><div class="pay-icon">💳</div><div><div class="pay-name">Visa / Mastercard</div><div class="pay-sub">Олон улсын карт</div></div><div class="pay-radio" id="radio-visa"></div></div>',
'</div>',
'<button class="btn-gold" onclick="doDeposit()">Цэнэглэх</button>',
'</div></div>',
'<div class="bottom-nav">',
'<div class="bnav" onclick="showPage(\'lobby\')"><div class="bnav-icon">🏠</div><div class="bnav-label">Лобби</div></div>',
'<div class="bnav" onclick="showPage(\'profile\')"><div class="bnav-icon">👤</div><div class="bnav-label">Профайл</div></div>',
'<div class="bnav active" onclick="showPage(\'wallet\')"><div class="bnav-icon">💰</div><div class="bnav-label">Данс</div></div>',
'</div></div>',

'<div class="page" id="page-game">',
'<div class="game-screen">',
'<div class="game-nav">',
'<button class="game-nav-btn" onclick="leaveGame()">← Гарах</button>',
'<div style="display:flex;flex-direction:column;align-items:center;">',
'<div class="game-title">♠ Royal Table</div>',
'<div class="game-phase" id="game-phase">Хүлээж байна</div>',
'</div>',
'<div style="font-size:12px;color:var(--gold);font-weight:600;">🪙 <span id="my-chips-val">0</span></div>',
'</div>',
'<div class="felt-area">',
'<div class="opp-seats" id="opps"></div>',
'<div class="table-oval">',
'<div class="pot-row">',
'<div class="pot-chip">🪙</div>',
'<div><div class="pot-lbl">Нийт пот</div><div class="pot-val" id="pot-display">0</div></div>',
'</div>',
'<div class="community-cards" id="community">',
'<div class="card-empty"></div><div class="card-empty"></div><div class="card-empty"></div><div class="card-empty"></div><div class="card-empty"></div>',
'</div></div>',
'<div class="my-hand-area">',
'<div class="my-hand-lbl">Таны карт</div>',
'<div class="my-cards" id="my-hand">',
'<div class="waiting-msg"><div class="waiting-icon">🃏</div><div class="waiting-txt waiting-dots">Тоглогчдыг хүлээж байна...</div></div>',
'</div></div></div>',
'<div class="action-panel">',
'<div class="table-info">',
'<div class="tbl-info-item">Блайнд <span class="tbl-info-val" id="blind-val">-</span></div>',
'<div class="tbl-info-item">Тоглогч <span class="tbl-info-val" id="player-count">0/6</span></div>',
'</div>',
'<div class="turn-indicator" id="turn-indicator"></div>',
'<div class="action-row">',
'<button class="action-btn btn-fold" onclick="act(\'fold\')">✕ Fold</button>',
'<button class="action-btn btn-check" onclick="act(\'check\')">— Check</button>',
'<button class="action-btn btn-call" onclick="act(\'call\',100)">↑ Call</button>',
'</div>',
'<div class="raise-row">',
'<input type="range" id="raise-slider" min="100" max="5000" value="500" step="100" class="raise-slider" oninput="updateRaise(this.value)"/>',
'<div class="raise-display" id="raise-display">500</div>',
'<button class="btn-raise" onclick="act(\'raise\',+document.getElementById(\'raise-slider\').value)">🔥 Raise</button>',
'</div>',
'<div class="deal-row">',
'<button class="deal-btn" onclick="act(\'deal_flop\')">Flop</button>',
'<button class="deal-btn" onclick="act(\'deal_turn\')">Turn</button>',
'<button class="deal-btn" onclick="act(\'deal_river\')">River</button>',
'</div>',
'</div>',
'<div class="game-log" id="game-log"></div>',
'</div></div>',

'<scr'+'ipt>',
'const SUITS={S:"♠",H:"♥",D:"♦",C:"♣"};',
'const RED={H:true,D:true};',
'const TABLES=[',
'{id:"room1",name:"Royal Grand",type:"holdem",blind:"1,000 / 2,000",mode:"virtual",max:6,players:3},',
'{id:"room2",name:"Diamond VIP",type:"holdem",blind:"10,000 / 20,000",mode:"real",max:6,players:1},',
'{id:"room3",name:"Bronze Hall",type:"holdem",blind:"100 / 200",mode:"virtual",max:9,players:5},',
'{id:"room4",name:"Five Card Elite",type:"fivecard",blind:"2,000 / 4,000",mode:"virtual",max:6,players:2},',
'{id:"room5",name:"High Roller Suite",type:"holdem",blind:"50,000 / 100,000",mode:"real",max:6,players:1},',
'{id:"room6",name:"Omaha Royale",type:"omaha",blind:"500 / 1,000",mode:"virtual",max:9,players:4},',
'{id:"room7",name:"Silver Lounge",type:"holdem",blind:"500 / 1,000",mode:"virtual",max:6,players:2},',
'];',
'let user=null,curRoom=null,curTable=null,socket=null,logItems=[],authTab="login",gamesPlayed=0,gamesWon=0,selAmount=10000,selPayMethod="qpay",myTurn=false;',

'function showPage(p){',
'document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));',
'document.getElementById("page-"+p).classList.add("active");',
'if(p==="profile")updateProfile();',
'const m={"lobby":"bnav-lobby","profile":"bnav-profile","wallet":"bnav-wallet"};',
'document.querySelectorAll(".bnav").forEach(b=>b.classList.remove("active"));',
'if(m[p]&&document.getElementById(m[p]))document.getElementById(m[p]).classList.add("active");',
'}',

'function switchTab(t){authTab=t;document.querySelectorAll(".tab").forEach((el,i)=>el.classList.toggle("active",i===(t==="login"?0:1)));document.getElementById("auth-btn").textContent=t==="login"?"Нэвтрэх":"Бүртгүүлэх";document.getElementById("bonus-tag").textContent=t==="register"?"🎁 Шинэ тоглогч 10,000 chip авна!":"";}',

'async function doAuth(){',
'const u=document.getElementById("auth-user").value.trim();',
'const p=document.getElementById("auth-pass").value.trim();',
'if(!u||!p){document.getElementById("auth-err").textContent="Нэр болон нууц үгээ оруулна уу";return;}',
'document.getElementById("auth-btn").textContent="...";',
'try{const res=await fetch("'+url+'/api/"+authTab,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:u,password:p})});',
'const data=await res.json();',
'if(data.error){document.getElementById("auth-err").textContent=data.error;document.getElementById("auth-btn").textContent=authTab==="login"?"Нэвтрэх":"Бүртгүүлэх";return;}',
'user=data;gamesPlayed=data.games||0;gamesWon=data.wins||0;',
'updateChips();renderTables("all");initSocket();showPage("lobby");',
'}catch(e){document.getElementById("auth-err").textContent="Сервертэй холбогдож чадсангүй";document.getElementById("auth-btn").textContent=authTab==="login"?"Нэвтрэх":"Бүртгүүлэх";}}',

'function updateChips(){document.getElementById("lobby-chips").textContent=Number(user.chips).toLocaleString();document.getElementById("w-chips").textContent=Number(user.chips).toLocaleString();document.getElementById("my-chips-val").textContent=Number(user.chips).toLocaleString();}',
'function getLevel(c){if(c>=100000)return"💎 DIAMOND";if(c>=50000)return"🥇 GOLD";if(c>=20000)return"🥈 SILVER";return"🥉 BRONZE";}',
'function updateProfile(){if(!user)return;document.getElementById("prof-avatar").textContent=user.username[0].toUpperCase();document.getElementById("prof-name").textContent=user.username;document.getElementById("stat-chips").textContent=Number(user.chips).toLocaleString();document.getElementById("stat-games").textContent=gamesPlayed;document.getElementById("stat-wins").textContent=gamesWon;document.getElementById("stat-rate").textContent=gamesPlayed?Math.round(gamesWon/gamesPlayed*100)+"%":"0%";document.getElementById("prof-level").textContent=getLevel(user.chips);}',
'function logout(){user=null;if(socket)socket.disconnect();showPage("auth");}',

'function renderTables(filter){',
'const list=document.getElementById("table-list");',
'const filtered=filter==="all"?TABLES:TABLES.filter(t=>t.type===filter||t.mode===filter);',
'list.innerHTML=filtered.map(t=>{',
'const seats=Array(t.max).fill(0).map((_,i)=>"<div class=\\"seat"+(i<t.players?" on":"")+"\\" ></div>").join("");',
'return "<div class=\\"tcard\\" onclick=\\"openJoinModal(\'"+t.id+"\')\\" ><div class=\\"tcard-shine\\"></div><div class=\\"tcard-top\\"><div class=\\"tcard-name\\">"+t.name+"</div><div class=\\"mbadge "+(t.mode==="virtual"?"virtual":"real")+"\\">"+( t.mode==="virtual"?"Virtual":"💰 Жинхэнэ")+"</div></div><div class=\\"tcard-info\\"><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Төрөл</div><div class=\\"tinfo-val\\">"+t.type+"</div></div><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Блайнд</div><div class=\\"tinfo-val\\">"+t.blind+"</div></div><div class=\\"tinfo\\"><div class=\\"tinfo-label\\">Тоглогч</div><div class=\\"tinfo-val\\">"+t.players+"/"+t.max+"</div></div></div><div class=\\"tcard-footer\\"><div class=\\"seat-row\\">"+seats+"<span class=\\"seat-count\\">"+t.players+"/"+t.max+"</span></div><button class=\\"join-btn\\">Нэгдэх →</button></div></div>";',
'}).join("");}',
'function filterTable(btn,f){document.querySelectorAll(".fpill").forEach(b=>b.classList.remove("active"));btn.classList.add("active");renderTables(f);}',

'function openJoinModal(id){',
'curRoom=id;',
'curTable=TABLES.find(t=>t.id===id);',
'document.getElementById("modal-table-name").textContent=curTable?curTable.name+" — "+curTable.blind:"";',
'document.getElementById("join-modal").classList.remove("hidden");',
'}',
'function closeModal(){document.getElementById("join-modal").classList.add("hidden");}',
'function confirmJoin(){',
'closeModal();',
'if(!curRoom||!user)return;',
'document.getElementById("pot-display").textContent="0";',
'document.getElementById("community").innerHTML="<div class=\\"card-empty\\"></div>".repeat(5);',
'document.getElementById("my-hand").innerHTML="<div class=\\"waiting-msg\\"><div class=\\"waiting-icon\\">🃏</div><div class=\\"waiting-txt waiting-dots\\">Тоглогчдыг хүлээж байна...</div></div>";',
'document.getElementById("opps").innerHTML="";',
'document.getElementById("turn-indicator").textContent="";',
'document.getElementById("game-phase").textContent="Хүлээж байна";',
'if(curTable){document.getElementById("blind-val").textContent=curTable.blind;document.getElementById("player-count").textContent="1/"+curTable.max;}',
'logItems=[];document.getElementById("game-log").innerHTML="";',
'if(socket)socket.emit("join_room",{room:curRoom,username:user.username});',
'gamesPlayed++;showPage("game");',
'}',
'function leaveGame(){if(socket&&curRoom)socket.emit("leave_room",{room:curRoom,username:user.username});showPage("lobby");}',

'function renderSeats(players,max){',
'const others=players.filter(p=>p.username!==user.username);',
'const empty=Math.max(0,max-others.length-1);',
'let html=others.map((p,i)=>{',
'return "<div class=\\"seat-wrap\\"><div class=\\"player-seat"+(!p.folded?" ":" folded")+"\\">"',
'+"<div class=\\"p-avatar\\">"+(i===0?"<div class=\\"dealer-d\\">D</div>":"")+p.username[0].toUpperCase()+"</div>"',
'+"<div class=\\"p-back-cards\\"><div class=\\"card-back\\"></div><div class=\\"card-back\\"></div></div>"',
'+"<div class=\\"p-name\\">"+p.username+"</div>"',
'+"<div class=\\"p-chips\\">"+Number(p.chips).toLocaleString()+" 🪙</div>"',
'+"</div></div>";',
'}).join("");',
'html+="<div class=\\"empty-seat-wrap\\"><div class=\\"empty-seat-icon\\">👤</div><div class=\\"empty-seat-txt\\">Хоосон</div></div>".repeat(empty);',
'return html;}',

'function initSocket(){',
'socket=io("'+url+'");',
'socket.on("room_update",r=>{',
'document.getElementById("opps").innerHTML=renderSeats(r.players,r.max||6);',
'document.getElementById("player-count").textContent=r.players.length+"/"+(r.max||6);',
'});',
'socket.on("game_started",r=>{',
'document.getElementById("pot-display").textContent="0";',
'document.getElementById("community").innerHTML="<div class=\\"card-empty\\"></div>".repeat(5);',
'document.getElementById("game-phase").textContent="Pre-flop";',
'document.getElementById("opps").innerHTML=renderSeats(r.players,r.max||6);',
'const me=r.players.find(p=>p.username===user.username);',
'if(me){',
'setTimeout(()=>{',
'document.getElementById("my-hand").innerHTML=me.hand.map((c,i)=>"<div class=\\"card deal"+(RED[c.suit]?" red":"")+" mine\\" style=\\"animation-delay:"+(i*0.15)+"s\\"><span class=\\"card-rank\\">"+c.rank+"</span><span class=\\"card-suit\\">"+SUITS[c.suit]+"</span></div>").join("");',
'},200);}',
'addLog("🃏 Карт таарагдлаа!");',
'});',
'socket.on("turn_update",({username})=>{',
'myTurn=username===user.username;',
'document.getElementById("turn-indicator").textContent=myTurn?"⭐ Таны ээлж!":username+" тоглож байна...";',
'});',
'socket.on("community_update",(cards)=>{',
'const phase=cards.length===3?"Flop":cards.length===4?"Turn":cards.length===5?"River":"";',
'document.getElementById("game-phase").textContent=phase;',
'const empty=5-cards.length;',
'document.getElementById("community").innerHTML=',
'cards.map((c,i)=>"<div class=\\"card deal"+(RED[c.suit]?" red":"")+"\\"><span class=\\"card-rank\\">"+c.rank+"</span><span class=\\"card-suit\\">"+SUITS[c.suit]+"</span></div>").join("")',
'+"<div class=\\"card-empty\\"></div>".repeat(empty);',
'addLog("♠ "+phase+" таарагдлаа");',
'});',
'socket.on("player_action",function(d){',
'if(d.pot)document.getElementById("pot-display").textContent=Number(d.pot).toLocaleString();',
'const icons={fold:"✕",call:"↑",raise:"🔥",check:"—"};',
'addLog((icons[d.action]||"")+" "+d.username+": "+d.action+(d.amount?" +"+Number(d.amount).toLocaleString()+" 🪙":""));',
'});',
'}',

'function act(a,amt){',
'if(socket&&curRoom)socket.emit("action",{room:curRoom,action:a,amount:amt,username:user.username});',
'}',
'function addLog(m){logItems=[m,...logItems].slice(0,3);document.getElementById("game-log").innerHTML=logItems.map(l=>"<div class=\\"log-item\\">"+l+"</div>").join("");}',
'function updateRaise(v){document.getElementById("raise-display").textContent=Number(v).toLocaleString();}',
'function selAmt(el,amt){document.querySelectorAll(".apill").forEach(p=>p.classList.remove("active"));el.classList.add("active");selAmount=amt;}',
'function selPay(el,method){document.querySelectorAll(".pay-method").forEach(p=>p.classList.remove("selected"));el.classList.add("selected");document.querySelectorAll(".pay-radio").forEach(r=>r.classList.remove("on"));const r=document.getElementById("radio-"+method);if(r)r.classList.add("on");selPayMethod=method;}',
'function doDeposit(){',
'const methods={qpay:"QPay",social:"SocialPay",khan:"Khan Bank",visa:"Visa/Mastercard"};',
'const name=methods[selPayMethod]||"QPay";',
'alert("✅ "+Number(selAmount).toLocaleString()+"₮ "+name+"-аар цэнэглэлт илгээгдлээ!\\n\\nТаны хүсэлт хянагдаж байна.");',
'}',
'</scr'+'ipt></body></html>'
].join("\n");

fs.writeFileSync('index.html', html);
console.log('Done! Size:', html.length);
